language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t naspuka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true naspuka/react-test npm test

after_success:
  - docker build -t naspuka/multi-client ./client
  - docker build -t naspuka/multi-nginx ./nginx
  - docker build -t naspuka/multi-server ./server
  - docker build -t naspuka/multi-worker ./worker

  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push naspuka/multi-client
  - docker push naspuka/multi-nginx
  - docker push naspuka/multi-server
  - docker push naspuka/multi-worker
